### PR TITLE
Fix segments evaluation

### LINKED ISSUE #180: Flagr segments evaluation should stop if it matches all the constraints in a segment
## Expected Behavior
If the entity context matches the constraints in a segment, it should stop evaluating the following segments.

Specifically, for 0% rollout segment, it shouldn't go to the next segments.

For example:

image

The first segment catches all the entity, and roll out to 0%, so every entity should have `null` variant returned.

## Current Behavior
It falls through to the next segment for non-rolled out users in the previous segments.

image

## Possible Solution
Stop evaluating the next segments if we found a match (i.e. satisfied all the constraints in a segment)

## Steps to Reproduce (for bugs)
https://try-flagr.herokuapp.com/#/flags/1

### PR DESCRIPTION
**Pull request by zhouzhuojie**
## Description
Fix #180 

This pr changed the behavior of segments fall-through logic. The intended behavior wad documented in https://checkr.github.io/flagr/#/flagr_use_cases

image

## How Has This Been Tested?
New multiple segments with 0% rollout flow.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: pkg/handler/eval_test.go [hunk 1]
```diff
@@ -171,6 +176,26 @@ func TestEvalFlag(t *testing.T) {
 		assert.NotNil(t, result.VariantID)
 	})
 
+	t.Run("test multiple segments with the first segment 0% rollout", func(t *testing.T) {
+		f := entity.GenFixtureFlag()
+		f.Segments = append(f.Segments, entity.GenFixtureSegment())
+		f.Segments[0].Constraints = []entity.Constraint{}
+		f.Segments[0].RolloutPercent = uint(0)
```
Comment (zhouzhuojie) [inline pkg/handler/eval_test.go]: The first segment says `0%` rollout for all entity (no constraints), thus the evaluation result should have `nil` variantID.

File: pkg/handler/eval.go [hunk 2]
```diff
@@ -220,14 +223,14 @@ var evalSegment = func(
 				Msg:       err.Error(),
 				SegmentID: int64(segment.ID),
 			}
-			return nil, log
+			return nil, log, true
```
Comment (rstratton) [inline pkg/handler/eval.go]: What kinds of errors do we expect from `conditions.Evaluate(expr, m)`?  Trying to understand why we should eval the next segment in this context
